ignore:
  - "./src/reportWebVitals.ts"  # ignore folders and all its contents
  - "./src/react-app-env.d.ts"  # ignore folders and all its contents

coverage:
  precision: 2
  round: up
  range: "60...75"