name: CD
on:
  push:
    branches: release

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Fix git
      run: |
        git config --global user.email "alexjhwoollam@gmail.com"
        git config --global user.name "Alex Woollam"

    - name: Install modules
      run: npm install

    - name: Install and Build 🔧
      run: npm run build
      env:
        REACT_APP_PASSWORD: ${{ secrets.REACT_APP_PASSWORD }}

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: deploy
        folder: build